production: &production
  discourse: https://forums.29th.org
  vanilla: https://vanilla.29th.org
  smf: https://smf.29th.org
  phpbb: https://phpbb.29th.org

development: &development
  <<: *production
  discourse: https://forums.29th.local
  vanilla: https://vanilla.29th.local

test:
  <<: *development
