host: www.29th.local
discourse:
  base_url:
    internal: http://host.docker.internal:3000
    external: http://forums.29th.local
  api_key: dev
  webhooks_secret: developmentsecret
  sso_secret: dev
  categories:
    enlistment_office: 4
service_coat_generator:
  base_url:
    internal: https://service-coat-generator-v82di.ondigitalocean.app
    external: https://service-coat-generator-v82di.ondigitalocean.app
  api_key: ~
vanilla:
  base_url:
    internal: https://forums
    external: https://vanilla.29th.local
smf:
  base_url:
    internal: https://smf
    external: https://smf.29th.local
storage:
  endpoint: ~
  bucket: ~
  region: ~
  access_key_id: ~
  secret_access_key: ~
  public_host: https://uploads.29th.org
