host: www.29th.org
discourse:
  base_url:
    internal: https://forums.29th.org
    external: https://forums.29th.org
  api_key: ~
  webhooks_secret: ~
  sso_secret: ~
  categories:
    enlistment_office: 37
service_coat_generator:
  base_url:
    internal: https://service-coat-generator-v82di.ondigitalocean.app
    external: https://service-coat-generator-v82di.ondigitalocean.app
  api_key: ~
vanilla:
  base_url:
    internal: https://vanilla.29th.org
    external: https://vanilla.29th.org
smf:
  base_url:
    internal: https://smf.29th.org
    external: https://smf.29th.org
storage:
  endpoint: ~
  bucket: ~
  region: ~
  access_key_id: ~
  secret_access_key: ~
  public_host: https://uploads.29th.org

