host: www.29th.local
discourse:
  base_url:
    internal: http://docker.host.internal:3000
    external: https://forums.29th.local
  api_key: test
  webhooks_secret: developmentsecret
  sso_secret: test
  categories:
    enlistment_office: ~
service_coat_generator:
  base_url:
    internal: https://service-coat-generator-v82di.ondigitalocean.app
    external: https://service-coat-generator-v82di.ondigitalocean.app
  api_key: ~
vanilla:
  base_url:
    internal: http://forums
    external: https://vanilla.29th.local
smf:
  base_url:
    internal: https://smf
    external: https://smf.29th.local
storage:
  endpoint: ~
  bucket: ~
  region: ~
  access_key_id: ~
  secret_access_key: ~
  public_host: https://uploads.29th.org
